site_name: Równania Różniczkowe

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Tryb automatyczny
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Jasny tryb
    - scheme: slate
      primary: indigo
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Ciemny tryb
  features:
    - palette.toggle
    - navigation.top
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - content.math

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      permalink: true
      
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Strona główna: index.md
  - Wstęp: Wstep.md
  - Równania różniczkowe I rzędu:
      - Wprowadzenie: rownania-rzedu-1.md
      - O zmiennych rozdzielonych:
          - Opis: metoda1-rzedu-1.md
          - Przykład: przyklad-metoda1-rzedu-1.md
      - Liniowe jednorodne: 
          - Opis: metoda2-rzedu-1.md
          - Przykład: przyklad-metoda2-rzedu-1.md
      - Liniowe niejednorodne:
          - Opis: metoda3-rzedu-1.md
          - Przykład: przyklad-metoda3-rzedu-1.md
      - Zupełne:
          - Opis: metoda4-rzedu-1.md
          - Przykład: przyklad-metoda4-rzedu-1.md
  - Równania różniczkowe II rzędu:
      - Wprowadzenie: rownania-rzedu-2.md
      - Liniowe jednorodne:
          - Opis: metoda1-rzedu-2.md
          - Przykład: przyklad-metoda1-rzedu-2.md
      - Liniowe niejednorodne:
          - Opis: metoda2-rzedu-2.md
          - Przykład: przyklad-metoda2-rzedu-2.md
  - Przykłady: przyklady.md
  - Autorzy: autorzy.md

plugins:
  - search

extra_css:
  - styles/custom.css
