site_name: RownaniaRozniczkowe

theme:
  name: ivory
  palette:
    scheme: default
    primary: purple   # fioletowy akcent
    accent: purple
  font:
    text: Georgia
    code: Fira Code
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - content.code.copy


# Struktura nawigacji (przykład) 
nav:
  - Strona główna: index.md
  - Wstęp: Wstep.md
  - Równania I rzędu: RRIstopien.md
  - Równania II rzędu: RRIIstopien.md
  - Przykłady: przyklady.md
  - Autorzy: autorzy.md

# Plugins
plugins:
  - search

extra_css: custom.css