site_name: Równania Różniczkowe

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Tryb automatyczny
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Jasny tryb
    - scheme: slate
      primary: indigo
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Ciemny tryb
  features:
    - palette.toggle
    - navigation.top
    - navigation.sections
    - content.code.copy

nav:
  - Strona główna: index.md
  - Wstęp: Wstep.md
  - Równania I rzędu: RRIstopien.md
  - Równania II rzędu: RRIIstopien.md
  - Przykłady: przyklady.md
  - Autorzy: autorzy.md

plugins:
  - search

extra_css:
  - styles/custom.css
extra_css:
  - styles/custom.css